### ISSUE TITLE
no @createthis email, cannot join slack

### ISSUE THREAD

**Issue by d3x0r** [createthis/mesh_maker_vr#2]
So ya... can't join slack.

You should just use gitter - it integrates so much better with github for sharing code.... and it can integrate with github to show commits/issues/pull requests etc...

**Comment by createthis** [comment]
Did you try the sign up link? https://meshmakervr.slack.com/signup

**Comment by d3x0r** [comment]
![image](https://user-images.githubusercontent.com/1909610/31253972-a6563186-a9db-11e7-8cae-63c8f3dc0d54.png)

**Comment by createthis** [comment]
What happens when you click "Don't have createthis.com email address?"

**Comment by d3x0r** [comment]
That's not clickable.  It says contact my administrator... which in this case would be You :)

**Comment by d3x0r** [comment]
if I fill in my name anyway...

An email is on its way.
d3x0r@createthis.com
When your email arrives, click the link provided to complete signup.

which I'll never get :)

**Comment by createthis** [comment]
Try this: https://join.slack.com/t/meshmakervr/shared_invite/enQtMjUyNDA4MTgxNTQxLTQwMmQzMDQzODUwYjdjOGVlMDRkY2NmZjczNWUzZGJkMjhkMzg3ZGM5YjBlMDZkOTAyMWNlYzhjYTNkOGY1YWU

**Comment by d3x0r** [comment]
that link worked (you should update the readme.md link )... 
https://github.com/createthis/mesh_maker_vr/blob/master/README.md  doesn't give me a line number :)

Slack is sitll much slower than gitter :)  https://gitter.im/  which just links to github account anyway...

**Comment by andybak** [comment]
Also worth bearing in mind that - as well as presenting barriers for initial access - any useful information in Slack discussions will probably end up lost forever. Compare that to discussions on mailing lists archived to the web - where you can look up tips and track discussions going back several decades when you need to.

I don't want to be all "get off my lawn" about new messaging platforms but mailing lists have worked well for open source for a long time and for good reasons.

**Comment by d3x0r** [comment]
google groups are easy to setup and work as a mailing list or forum.

**Comment by createthis** [comment]
Whoa, now there are two of you! We've doubled our user base!

Slack is intended for real time communications. Mailing lists are slower. As a developer, I've never really liked mailing lists. You have to subscribe, filter the mail, wait for replies, etc. With Slack you just pop in and ask a question. It takes the place of IRC in the old way of doing things but it's easier to use than IRC (no client necessary, no esoteric commands). I've used Slack to communicate with developers in my team at my day job for years. It's the gold standard in that arena.

The signal to noise ratio in a mailing list tends to be low. We have the README and the wiki for permanent knowledge storage, so I'd argue the permanent storage value of a mailing list is moot.

I've never used Gitter before, but I've used Discord, and I like Discord too. The Hush coin Slack recently switched to Discord because we had a scammer problem and Slack didn't provide a mechanism to stop it. If we start having similar problems we can certainly switch.

I've updated the README with the new link.
